- README.md
> adding to the readme

- Team-Contract.md
> Add Team-Contract.md document

- package.json
> heroku deployment

- README.md
> messing around with readme

- README.md
> added waffle.io badge

- package-lock.json
- package.json
- script/seed.js
- server/api/users.js
- server/api/users.spec.js
- server/db/models/user.js
- server/db/models/user.spec.js
- server/index.js
- server/middlewares/index.js
- server/middlewares/user.js
Updated user model to include user role
Added function to check user 'access level' - based on role
Added middlewares to permit users to use specific routes
Added /users/:userId admin route to grab all user information
* [NO] added unit tests (or none needed)
---
> added user roles/permissions middlewares

- script/seed.js
- server/db/models/index.js
- server/db/models/orders.js
- server/db/models/product.js
- server/db/models/review.js
- server/db/models/user.js
add orders, product, review, user, index db models
Beware of merge conflicts.
Needs unit tests.
> feat(database): add models and associations

- server/api/index.js
- server/api/products.js
> bare minimum for product routes

- server/auth/google.js
- server/index.js
Hardcoded our emails into user creation so that our role defaults to dev instead of user.
> feature: add auto-dev

- server/db/models/review.js
> Bug(db): Add starRating field on Review model

- server/db/models/product.js
- server/db/models/review.js
> Add avg rating to db

- client/store/products.js
- server/api/cart.js
- server/api/products.js
> feature: redux products and categories

- server/db/models/order.js
- server/db/models/review.js
- server/seed/reviews.json
> Bugfix rating hook

- client/components/Navbar.js
- client/components/SingleJelly.js
- client/components/admin/EditJellyForm.js
- client/components/index.js
- client/store/jellies.js
- server/api/jellies.js
need to implement categories, roadblocked by AddJellyForm
---
> FEATURE edit jellies

- FIRST-CODE-REVIEW.md
- client/components/Toolbar.js
- client/store/user.js
Add dropdown, redux functionality to it and notes from first code review.
> Refine product #16

- client/components/JellyList.js
- client/components/Toolbar.js
- client/routes.js
- client/store/cart.js
- client/store/index.js
- client/store/jellies.js
- client/store/user.js
- server/api/cart.js
- server/auth/index.js
- server/db/models/user.js
> fix search.search

- client/components/BootNavbar.js
- client/components/DNU_Navbar.js
- client/components/SingleJelly.js
- client/components/Toolbar.js
- client/components/index.js
- client/store/cart.js
- package.json
- server/api/cart.js
- server/db/models/jelly.js
- server/db/models/jellyOrder.js
- server/db/models/order.js
- server/db/models/user.js
- server/seed/seed.spec.js
> F/cart feature #27

- client/components/JellyList.js
- client/components/SingleJelly.js
- client/components/admin/AddJellyForm.js
- client/components/admin/EditJellyForm.js
- server/api/cart.js
- server/api/cartSession.js
- server/db/models/jelly.js
- server/db/models/jellyOrder.js
- server/seed/jellies.json
> Price=>price cents

- client/components/AccessBar.js
- client/components/Homepage.js
- client/components/Homepage.spec.js
- client/routes.js
> fixed root path / display

- client/components/JellyList.js
- client/components/admin/AdminLanding.js
- client/components/admin/AllOrders.js
- server/api/cart.js
- server/api/cartSession.js
- server/api/orders.js
---
- fixed jelly list add quantity 
- added all order view for admins
> fixed jellylist add to cart and added some admin order views

- client/components/CartView.js
- client/components/JellyList.js
- public/style.css
- `Delete` link on cart item needs functionality
- Increment and decrement quantity buttons need link to add item/remove item routes
> Fix footer #103

- client/components/CartView.js
- client/components/admin/AllOrders.js
- client/store/cart.js
- client/store/jellies.js
- server/api/cart.js
- server/api/cartSession.js
- server/api/orders.js
- server/auth/index.js
---
-finalize admin order tool
> Order branch

- client/components/AddressForm.js
- client/components/CartView.js
- client/components/CheckoutSplash.js
- client/components/FinalCheckout.js
- client/components/StripeForm.js
- client/components/index.js
- client/routes.js
- client/store/cart.js
- client/store/user.js
- server/api/cart.js
- server/api/users.js
- server/auth/index.js
- server/db/models/address.js
- server/db/models/index.js
- server/db/models/user.js
> Checkout splash page

- client/components/CartView.js
- client/components/JellyList.js
- client/components/Toolbar.js
- client/components/admin/AllOrders.js
- client/store/cart.js
- client/store/jellies.js
- server/api/cart.js
- server/api/cartSession.js
- server/api/orders.js
- server/api/orders.spec.js
- server/db/models/jellyOrder.js
> Cart fully functional (knock on wood)

- client/components/AddressForm.js
- client/components/CheckoutSplash.js
- client/components/FinalCheckout.js
- client/components/JellyReviews.js
- client/components/SingleJelly.js
- client/components/StripeForm.js
- server/api/jellies.spec.js
> User page #128
